{% set name = "jupyter-offlinenotebook" %}
{% set pypiname = name.replace('-', '_') %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: 8000498e17e59cb1e85756f2f7ed2755a0f4e92d581c480ffe7c2da91d8fbf16

build:
  number: 0
  noarch: python
  script:
    - export YARN_ENABLE_IMMUTABLE_INSTALLS=false
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - nodejs *
  host:
    # JupyterLab 3 is required for building since jlpm is used to compile the javscript assets, but the resulting package works with Notebook, JupyterLab 2, JupyterLab 3
    - jupyter-packaging >=0.7.9
    - jupyterlab >=3
    - pip
    - python >=3.7
    - wheel
  run:
    # This package also includes an extension for JupyterLab 3
    - jupyter_server
    - python >=3.7

test:
  imports:
    - jupyter_offlinenotebook
  requires:
    - pip
  commands:
    - python -m pip check

about:
  home: https://github.com/manics/jupyter-offlinenotebook
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - LICENSE.dexie
  summary: Save and load notebooks to local-storage. Supports Notebook and JupyterLab.

extra:
  recipe-maintainers:
    - manics
    - xhochy
