{% set name = "jupyter-offlinenotebook" %}
{% set pypiname = name.replace('-', '_') %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: 914f9c72f1c085f4a771b61ad28b7ee737a7e1b613388ec74556815c8eb93d3b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    # JupyterLab 3 is required for building since jlpm is used to compile the javscript assets, but the resulting package works with Notebook, JupyterLab 2, JupyterLab 3
    - jupyter-packaging >=0.7.9
    - jupyterlab >=3
    - nodejs
    - pip
    - python >=3.6
  run:
    # This package also includes an extension for JupyterLab 3
    - jupyter_server
    - notebook
    - python >=3.6

test:
  imports:
    - jupyter_offlinenotebook
  requires:
    - pip
  commands:
    - python -m pip check

about:
  home: https://github.com/manics/jupyter-offlinenotebook
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - LICENSE.dexie
  summary: Save and load notebooks to local-storage. Supports Notebook and JupyterLab.

extra:
  recipe-maintainers:
    - manics
    - xhochy
