{% set name = "jupyter-offlinenotebook" %}
{% set pypiname = name.replace('-', '_') %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: 914f9c72f1c085f4a771b61ad28b7ee737a7e1b613388ec74556815c8eb93d3b

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-build-isolation --no-deps -vv

requirements:
  host:
    - jupyter-packaging ~=0.12.3
    # JupyterLab is required for building since jlpm is used to compile the javascript assets
    # but the resulting package works with Notebook and JupyterLab
    - jupyterlab ~=4.0
    - nodejs >=18
    - pip
    - python >=3.7
    - setuptools-scm >=8
    - wheel
  run:
    - jupyter_server
    - python >=3.7
  run_constrained:
    - jupyterlab >=3,<5

test:
  imports:
    - jupyter_offlinenotebook
  requires:
    - jupyterlab
    - pip
  commands:
    - python -m pip check
    - jupyter labextension list 2>&1 | grep -e 'jupyter-offlinenotebook.*enabled'
    - jupyter server extension list 2>&1 | grep -e 'jupyter_offlinenotebook.*enabled'

about:
  home: https://github.com/manics/jupyter-offlinenotebook
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - LICENSE.dexie
  summary: Save and load notebooks to local-storage. Supports Notebook and JupyterLab.

extra:
  recipe-maintainers:
    - manics
    - xhochy
